// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-OK1QRe7QZP3P53G7sfwx6Tff7AbG0BU',
    appId: '1:669731608512:android:a6097354c8bb99f4f9da25',
    messagingSenderId: '669731608512',
    projectId: 'horoscopeapp-ab19f',
    databaseURL: 'https://horoscopeapp-ab19f-default-rtdb.firebaseio.com',
    storageBucket: 'horoscopeapp-ab19f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLrDerv7c3mSEsnsNUaf7sActArGjXBWQ',
    appId: '1:669731608512:ios:222bf4812d502ea8f9da25',
    messagingSenderId: '669731608512',
    projectId: 'horoscopeapp-ab19f',
    databaseURL: 'https://horoscopeapp-ab19f-default-rtdb.firebaseio.com',
    storageBucket: 'horoscopeapp-ab19f.appspot.com',
    iosBundleId: 'com.example.horoscopeApp',
  );
}
